### ISSUE TITLE
Weak scaling inconsistent between small, medium, large, very_large

### ISSUE THREAD

**Issue by edbennett** [sa2c/sombrero#2]
Weak scaling is defined in `sombrero/sombrero.c` as follows

* If size is medium, then L = 24 and T = number of ranks
* If size is large, then L = 48 and T = number of ranks
* Otherwise, local volume is 4^4, with the parallelisation being decided by `weak_scale_lattice`.

It seems strange that medium and large are in one regime, but small and very_large are in another. In particular, that very_large is in fact no different to small. 

I would suggest that a very_large weak case be added, perhaps with L = 64 or 96. Having the small case available (in particular to judge scaling from a single rank upwards) is still probably useful.

**Comment by mmesiti** [comment]
I agree this change would improve consistency. For sure this
> In particular, that very_large is in fact no different to small.

sounds obviously counter intuitive.
